/* generated by tools/build-levels.js; each level re-solved exactly (par = fewest watcher actions) */
window.PRISON_LEVELS = [
 {
  "id": 1,
  "map": [
   "#####",
   "#S#v#",
   "#.#E#",
   "#.#.#",
   "#...#",
   "#####"
  ],
  "meta": {},
  "par": 1,
  "src": "hand 1"
 },
 {
  "id": 2,
  "map": [
   ">....",
   "..>E#",
   "...#.",
   "S....",
   "....#"
  ],
  "meta": {
   "guards": {}
  },
  "par": 2,
  "src": "gen 5x5 s1"
 },
 {
  "id": 3,
  "map": [
   "....S",
   ".....",
   ".^...",
   "..#..",
   "#E<.."
  ],
  "meta": {
   "guards": {}
  },
  "par": 2,
  "src": "gen 5x5 s10"
 },
 {
  "id": 4,
  "map": [
   "....a.",
   "..>.a#",
   ".<#.aE",
   ".#....",
   ".S#..."
  ],
  "meta": {
   "guards": {
    "a": {
     "i": 1,
     "f": 0,
     "range": 3
    }
   }
  },
  "par": 3,
  "src": "gen 6x5 s21"
 },
 {
  "id": 5,
  "map": [
   "E.a#..",
   "^#a.#.",
   ".#a...",
   "..S...",
   "..#..."
  ],
  "meta": {
   "guards": {
    "a": {
     "i": 0,
     "f": 1,
     "range": 3
    }
   }
  },
  "par": 3,
  "src": "gen 6x5 s22"
 },
 {
  "id": 6,
  "map": [
   "...E<",
   "...#S",
   "#.>..",
   ".....",
   "....."
  ],
  "meta": {
   "guards": {}
  },
  "par": 3,
  "src": "gen 5x5 s14"
 },
 {
  "id": 7,
  "map": [
   "..##..",
   "..#S..",
   ".E.v..",
   ".aaaa.",
   "....^."
  ],
  "meta": {
   "guards": {
    "a": {
     "i": 3,
     "f": 0,
     "range": 3
    }
   }
  },
  "par": 5,
  "src": "gen 6x5 s24"
 },
 {
  "id": 8,
  "map": [
   "...va.",
   "#..Ea.",
   "..##a<",
   "#bbba.",
   "...^#S",
   ".....#"
  ],
  "meta": {
   "guards": {
    "a": {
     "i": 2,
     "f": 0,
     "range": 3
    },
    "b": {
     "i": 0,
     "f": 0,
     "range": 3
    }
   }
  },
  "par": 5,
  "src": "gen 6x6 s111"
 },
 {
  "id": 9,
  "map": [
   ".ccc...",
   ".#..<..",
   ".E.>.a.",
   "..^.ba#",
   ".^#.baS",
   ".#..ba.",
   "..##..."
  ],
  "meta": {
   "guards": {
    "a": {
     "i": 0,
     "f": 0,
     "range": 3
    },
    "b": {
     "i": 2,
     "f": 1,
     "range": 3
    },
    "c": {
     "i": 1,
     "f": 0,
     "range": 3
    }
   }
  },
  "par": 8,
  "src": "gen 7x7 s211"
 }
];
