/* Merges generated level files, re-solves every level exactly and writes play/levels.js.
   usage: node tools/build-levels.js out.js part1.jsonl part2.jsonl ... */
'use strict';
const fs = require('fs'), P = require('../src/prison.js');
const [out, ...files] = process.argv.slice(2);
const byN = new Map();
for (const f of files) for (const l of fs.readFileSync(f, 'utf8').split('\n')) if (l.trim()) { const d = JSON.parse(l); byN.set(d.n, d); }
const levels = [];
let missing = [];
for (let n = 1; n <= 120; n++) {
  const d = byN.get(n);
  if (!d) { missing.push(n); continue; }
  const L = P.parseLevel(d.map, d.meta); P.prepare(L);
  const r = P.solve(L, { maxDepth: 40 });
  if (!r || !r.solvable) { console.error('UNSOLVABLE', n); missing.push(n); continue; }
  if (r.par !== d.par) console.error('par differs', n, d.par, r.par);
  levels.push({ id: n, map: d.map, meta: d.meta, par: r.par });
}
fs.writeFileSync(out, '/* generated by tools/gen-levels.js + tools/build-levels.js; every level re-solved exactly (par = fewest actions) */\nwindow.PRISON_LEVELS = ' + JSON.stringify(levels) + ';\n');
console.log(levels.length + ' levels written' + (missing.length ? '; missing: ' + missing.join(',') : ''));
console.log('par by block:', Array.from({ length: 12 }, (_, b) => levels.filter(l => Math.floor((l.id - 1) / 10) === b).map(l => l.par).join(' ')).join(' | '));
