/* Picks the shipped levels from candidate files, re-solves each one and writes play/levels.js.
   usage: node tools/build-levels.js out.js cand1.jsonl cand2.jsonl ... */
const fs = require('fs'), P = require('../src/prison.js');
const [out, ...files] = process.argv.slice(2);
const all = [];
for (const f of files) for (const l of fs.readFileSync(f, 'utf8').trim().split('\n')) if (l) all.push(JSON.parse(l));
const hand = [{ name: 'hand 1', map: ['#####', '#S#v#', '#.#E#', '#.#.#', '#..##'.replace('##', '.#'), '#####'], meta: {} }];
const guardy = d => d.map.some(r => /[a-d]/.test(r));
const pick = (pred, n, from) => from.filter(pred).slice(0, n);
const byPar = (a, b) => a.par - b.par || a.name.localeCompare(b.name);
const small = all.filter(d => d.name.includes('5x5') || d.name.includes('6x5') || (d.name.includes('6x6') && d.par <= 5 && d.used <= 3));
const big = all.filter(d => !small.includes(d));
const chosen = [];
chosen.push(...hand.map(h => Object.assign(h, { par: 1, used: 1 })));
chosen.push(...pick(d => d.par === 2 && !guardy(d), 2, small.sort(byPar)));
chosen.push(...pick(d => d.par === 2 && guardy(d), 1, small.sort(byPar)));
chosen.push(...pick(d => d.par === 3 && guardy(d), 2, small.sort(byPar)));
chosen.push(...pick(d => d.par === 3 && !guardy(d), 1, small.sort(byPar)));
chosen.push(...pick(d => d.par === 4, 1, small.sort(byPar)));
chosen.push(...pick(d => d.par === 5, 1, small.sort(byPar)));
chosen.push(...pick(d => d.par === 5 && d.used >= 4, 2, big.sort(byPar)));
chosen.push(...pick(d => d.par >= 8 && d.used >= 4, 2, big.sort(byPar)));
const levels = [];
for (const d of chosen) {
  const L = P.parseLevel(d.map, d.meta || {});
  P.prepare(L);
  const r = P.solve(L, { maxDepth: 40 });
  if (!r || !r.solvable) { console.error('SKIP unsolvable', d.name); continue; }
  levels.push({ id: levels.length + 1, map: d.map, meta: d.meta || {}, par: r.par, src: d.name });
}
levels.sort((a, b) => a.par - b.par || a.id - b.id);
levels.forEach((l, i) => { l.id = i + 1; });
fs.writeFileSync(out, '/* generated by tools/build-levels.js; each level re-solved exactly (par = fewest watcher actions) */\nwindow.PRISON_LEVELS = ' + JSON.stringify(levels, null, 1) + ';\n');
console.log(levels.map(l => `#${l.id}:par${l.par}`).join(' '));
